import React from "react";
import { Link } from "react-router-dom";
import { Shield, Sparkles, Activity, ArrowUpRight, Cpu, CheckCircle2, Lock, Eye, Database } from "lucide-react";

export const UnrushedKnowledgeSection: React.FC = () => {
  const principles = [
    {
      number: "01",
      title: "Signal Above Velocity",
      subtitle: "Why 90% of crypto participants lose money chasing ticks",
      description:
        "High-frequency market feeds are deliberately designed to trigger dopamine and reactionary trading. In digital assets, true asymmetric alpha develops over multi-week structural capital cycles, not 5-minute candlestick wicks.",
      takeaway:
        "Our ingestion pipeline processes 100,000 mempool events every second, applying mathematical noise-reduction filters to isolate the 3 verifiable wallet clusters that actually move macro markets.",
      icon: Activity,
      stat: "99.8% Noise Filtered",
    },
    {
      number: "02",
      title: "Multi-Model Neural Consensus",
      subtitle: "Eliminating hallucination through adversarial cross-validation",
      description:
        "Relying on a single AI model or indicator is catastrophic during black-swan liquidity shocks. CryptoVision synthesizes distinct transformer architectures—evaluating on-chain mempool velocity, macro liquidity, and developer code commits independently.",
      takeaway:
        "Only when all three independent neural reasoning paths converge above a 90% confidence threshold does the system emit an institutional alpha conviction dossier.",
      icon: Cpu,
      stat: "98.4% Model Alignment",
    },
    {
      number: "03",
      title: "Verifiable Cryptographic Truth",
      subtitle: "Never trust proprietary black-boxes without raw block hashes",
      description:
        "Wall Street relies on opaque private ledgers; digital assets offer thermodynamic, immutable transparency. Every insight, whale alert, and risk calculation generated by CryptoVision links directly to reproducible on-chain transaction hashes.",
      takeaway:
        "No sentiment guessing, no influencer bias, and no undisclosed commercial sponsorships. Pure mathematical provenance recorded on decentralized ledgers.",
      icon: Shield,
      stat: "100% On-Chain Proofs",
    },
  ];

  return (
    <section id="philosophy" className="relative py-20 lg:py-28 bg-[#080809] text-white border-t border-white/10 overflow-hidden">
      
      {/* Background Ambient Glow */}
      <div className="pointer-events-none absolute -top-40 right-1/4 w-[500px] h-[500px] rounded-full bg-[#00dc82]/[0.02] blur-[150px]" />
      
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header with Editorial Serif */}
        <div className="max-w-3xl mb-16 sm:mb-20">
          <span className="font-mono text-xs uppercase tracking-[0.25em] text-[#00dc82] block mb-3">
            The Philosophy of Composure
          </span>
          <h2 className="font-editorial text-3xl sm:text-4xl lg:text-5xl font-normal text-white leading-tight">
            How systematic allocators build unshakeable conviction.
          </h2>
          <p className="mt-4 text-sm sm:text-base text-white/60 font-sans leading-relaxed">
            Market volatility is not a hazard to be feared; it is the natural consequence of 24/7 global price discovery. The allocator's only defense is an unhurried, mathematically sound decision framework.
          </p>
        </div>

        {/* The Three Editorial Principles */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 lg:gap-10">
          {principles.map((p) => {
            const Icon = p.icon;
            return (
              <div
                key={p.number}
                className="serene-card rounded-3xl p-7 sm:p-8 flex flex-col justify-between group transition-all"
              >
                <div>
                  {/* Top Bar: Number + Stat Badge */}
                  <div className="flex items-center justify-between border-b border-white/10 pb-4 mb-6">
                    <span className="font-editorial text-2xl text-white/40 group-hover:text-white transition-colors">
                      {p.number}
                    </span>
                    <span className="text-[10px] font-mono font-semibold text-[#00dc82] bg-[#00dc82]/10 border border-[#00dc82]/20 px-2.5 py-1 rounded-full">
                      {p.stat}
                    </span>
                  </div>

                  {/* Title & Subtitle */}
                  <h3 className="font-editorial text-2xl sm:text-3xl text-white mb-2 leading-snug">
                    {p.title}
                  </h3>
                  <div className="text-xs font-mono text-[#00dc82]/80 uppercase tracking-wider mb-4">
                    {p.subtitle}
                  </div>

                  {/* Body Copy */}
                  <p className="text-xs sm:text-sm text-white/60 font-sans leading-relaxed mb-4">
                    {p.description}
                  </p>

                  <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 text-xs text-white/75 font-sans leading-relaxed">
                    <strong className="text-white font-medium block mb-1">Methodology:</strong>
                    {p.takeaway}
                  </div>
                </div>

                {/* Bottom link */}
                <div className="mt-8 pt-4 border-t border-white/5 flex items-center justify-between text-xs font-mono text-white/40 group-hover:text-white transition-colors">
                  <span>Explore Architecture</span>
                  <ArrowUpRight className="h-4 w-4 text-white/30 group-hover:text-[#00dc82] transition-colors" />
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
