export interface HistoricalDataPoint {
  assetId: string;
  symbol: string;
  name: string;
  period: "1D" | "7D" | "30D" | "90D" | "1Y" | "CUSTOM";
  startDate: string;
  endDate: string;
  startPriceUsd: number;
  endPriceUsd: number;
  usdChangePercent: number;
  volatilityAnnualized: number; // e.g. 48.5%
  maxDrawdownPeriod: number; // e.g. -14.2%
  largestOneDayMove: number; // e.g. +8.9%
  dataProvider: string;
  eventsTimeline: { title: string; date: string; category: string; description: string }[];
}

export const HISTORICAL_ASSET_DATABASE: Record<string, Record<string, HistoricalDataPoint>> = {
  kryptos: {
    "1D": {
      assetId: "kryptos",
      symbol: "KRYPTOS",
      name: "Kryptos Protocol",
      period: "1D",
      startDate: "2026-09-05T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 95712.0,
      endPriceUsd: 104250.0,
      usdChangePercent: 8.92,
      volatilityAnnualized: 42.1,
      maxDrawdownPeriod: -2.1,
      largestOneDayMove: 8.92,
      dataProvider: "CryptoVision Direct Mempool Telemetry & CoinGecko",
      eventsTimeline: [
        {
          title: "Sovereign Treasury Absorption Event",
          date: "Sep 5, 2026",
          category: "Custody",
          description: "Institutional cold-storage absorption exceeded daily network issuance by 4.2x, causing liquid free float on exchanges to drop below 8.4%.",
        },
        {
          title: "4K Node Consensus Saturation",
          date: "Sep 6, 2026",
          category: "Protocol",
          description: "4K sovereign node validators confirmed sub-1.8ms execution finality with zero block reorganizations.",
        },
      ],
    },
    "7D": {
      assetId: "kryptos",
      symbol: "KRYPTOS",
      name: "Kryptos Protocol",
      period: "7D",
      startDate: "2026-08-30T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 89400.0,
      endPriceUsd: 104250.0,
      usdChangePercent: 16.61,
      volatilityAnnualized: 48.5,
      maxDrawdownPeriod: -4.8,
      largestOneDayMove: 8.92,
      dataProvider: "CryptoVision Direct Mempool Telemetry & CoinGecko",
      eventsTimeline: [
        {
          title: "Global Central Bank Liquidity Injection",
          date: "Sep 2, 2026",
          category: "Macro",
          description: "Global M2 money supply expanded by $420B, accelerating institutional allocations into unencumbered cryptographic reserve assets.",
        },
      ],
    },
    "30D": {
      assetId: "kryptos",
      symbol: "KRYPTOS",
      name: "Kryptos Protocol",
      period: "30D",
      startDate: "2026-08-07T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 78200.0,
      endPriceUsd: 104250.0,
      usdChangePercent: 33.31,
      volatilityAnnualized: 52.4,
      maxDrawdownPeriod: -9.5,
      largestOneDayMove: 11.4,
      dataProvider: "CryptoVision Direct Mempool Telemetry & CoinGecko",
      eventsTimeline: [
        {
          title: "Pectra-Level Cross-Validation Mainnet Launch",
          date: "Aug 18, 2026",
          category: "Upgrade",
          description: "Adversarial neural consensus model successfully deployed across 18 co-located global RPC nodes.",
        },
      ],
    },
    "90D": {
      assetId: "kryptos",
      symbol: "KRYPTOS",
      name: "Kryptos Protocol",
      period: "90D",
      startDate: "2026-06-08T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 64500.0,
      endPriceUsd: 104250.0,
      usdChangePercent: 61.63,
      volatilityAnnualized: 56.8,
      maxDrawdownPeriod: -14.2,
      largestOneDayMove: 12.8,
      dataProvider: "CryptoVision Direct Mempool Telemetry & CoinGecko",
      eventsTimeline: [
        {
          title: "Institutional Custody Framework Standardized",
          date: "Jul 12, 2026",
          category: "Regulation",
          description: "Tier-1 global custodian banks enabled native multi-sig vault settlement for sovereign treasuries.",
        },
      ],
    },
    "1Y": {
      assetId: "kryptos",
      symbol: "KRYPTOS",
      name: "Kryptos Protocol",
      period: "1Y",
      startDate: "2025-09-06T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 42000.0,
      endPriceUsd: 104250.0,
      usdChangePercent: 148.21,
      volatilityAnnualized: 64.2,
      maxDrawdownPeriod: -22.5,
      largestOneDayMove: 16.4,
      dataProvider: "CryptoVision Direct Mempool Telemetry & CoinGecko",
      eventsTimeline: [
        {
          title: "Sovereign Reserve Asset Declaration",
          date: "Nov 14, 2025",
          category: "Adoption",
          description: "First multi-national sovereign wealth fund allocated 2.5% of total capital reserve to Kryptos Protocol.",
        },
      ],
    },
  },
  btc: {
    "1D": {
      assetId: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      period: "1D",
      startDate: "2026-09-05T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 92635.0,
      endPriceUsd: 96480.0,
      usdChangePercent: 4.15,
      volatilityAnnualized: 36.4,
      maxDrawdownPeriod: -1.4,
      largestOneDayMove: 4.15,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Spot ETF Net Inflow Acceleration",
          date: "Sep 5, 2026",
          category: "Institutional",
          description: "$840M single-day net ETF inflows absorbed exchange order books across US & European exchanges.",
        },
      ],
    },
    "7D": {
      assetId: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      period: "7D",
      startDate: "2026-08-30T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 88500.0,
      endPriceUsd: 96480.0,
      usdChangePercent: 9.02,
      volatilityAnnualized: 40.1,
      maxDrawdownPeriod: -3.2,
      largestOneDayMove: 4.15,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Hashrate All-Time High",
          date: "Sep 1, 2026",
          category: "Network",
          description: "Bitcoin computational security reached 680 EH/s following next-gen mining deployment in Texas & Nordic regions.",
        },
      ],
    },
    "30D": {
      assetId: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      period: "30D",
      startDate: "2026-08-07T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 81200.0,
      endPriceUsd: 96480.0,
      usdChangePercent: 18.82,
      volatilityAnnualized: 44.5,
      maxDrawdownPeriod: -6.8,
      largestOneDayMove: 7.2,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Central Bank Rate Cuts Announced",
          date: "Aug 15, 2026",
          category: "Macro",
          description: "Global rate-cut cycle triggered capital rebalancing from low-yield government bonds to sovereign digital assets.",
        },
      ],
    },
    "90D": {
      assetId: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      period: "90D",
      startDate: "2026-06-08T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 68400.0,
      endPriceUsd: 96480.0,
      usdChangePercent: 41.05,
      volatilityAnnualized: 49.2,
      maxDrawdownPeriod: -12.1,
      largestOneDayMove: 8.9,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Exchange Reserve Multi-Year Low",
          date: "Jul 4, 2026",
          category: "On-Chain",
          description: "Centralized exchange BTC reserves fell below 2.18M BTC, the lowest level recorded since 2017.",
        },
      ],
    },
    "1Y": {
      assetId: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      period: "1Y",
      startDate: "2025-09-06T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 54200.0,
      endPriceUsd: 96480.0,
      usdChangePercent: 78.01,
      volatilityAnnualized: 52.8,
      maxDrawdownPeriod: -18.4,
      largestOneDayMove: 11.2,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Halving Supply Squeeze Emergence",
          date: "Jan 10, 2026",
          category: "Supply",
          description: "Post-halving daily issuance constraint of 450 BTC/day led to persistent structural market deficit.",
        },
      ],
    },
  },
  eth: {
    "1D": {
      assetId: "eth",
      symbol: "ETH",
      name: "Ethereum",
      period: "1D",
      startDate: "2026-09-05T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 3236.65,
      endPriceUsd: 3420.5,
      usdChangePercent: 5.68,
      volatilityAnnualized: 45.2,
      maxDrawdownPeriod: -1.8,
      largestOneDayMove: 5.68,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Pectra Testnet Finalization",
          date: "Sep 5, 2026",
          category: "Protocol",
          description: "EIP-7702 account abstraction features passed security audit with 100% validator consensus.",
        },
      ],
    },
    "7D": {
      assetId: "eth",
      symbol: "ETH",
      name: "Ethereum",
      period: "7D",
      startDate: "2026-08-30T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 3080.0,
      endPriceUsd: 3420.5,
      usdChangePercent: 11.05,
      volatilityAnnualized: 49.0,
      maxDrawdownPeriod: -3.8,
      largestOneDayMove: 5.68,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "DeFi TVL Surpasses $60B",
          date: "Sep 2, 2026",
          category: "DeFi",
          description: "Total value locked across Ethereum layer 1 and rollups set a new 2-year record high.",
        },
      ],
    },
    "30D": {
      assetId: "eth",
      symbol: "ETH",
      name: "Ethereum",
      period: "30D",
      startDate: "2026-08-07T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 2820.0,
      endPriceUsd: 3420.5,
      usdChangePercent: 21.3,
      volatilityAnnualized: 54.1,
      maxDrawdownPeriod: -7.5,
      largestOneDayMove: 8.4,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Staked ETH Ratio Reaches 28.6%",
          date: "Aug 20, 2026",
          category: "Staking",
          description: "34.5M ETH locked securing the Proof-of-Stake consensus engine.",
        },
      ],
    },
    "90D": {
      assetId: "eth",
      symbol: "ETH",
      name: "Ethereum",
      period: "90D",
      startDate: "2026-06-08T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 2450.0,
      endPriceUsd: 3420.5,
      usdChangePercent: 39.61,
      volatilityAnnualized: 58.6,
      maxDrawdownPeriod: -15.8,
      largestOneDayMove: 10.1,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Institutional Staking ETF Filings",
          date: "Jul 10, 2026",
          category: "Regulation",
          description: "Major asset managers submitted amended S-1 applications incorporating validator staking yield.",
        },
      ],
    },
    "1Y": {
      assetId: "eth",
      symbol: "ETH",
      name: "Ethereum",
      period: "1Y",
      startDate: "2025-09-06T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 2150.0,
      endPriceUsd: 3420.5,
      usdChangePercent: 59.09,
      volatilityAnnualized: 62.4,
      maxDrawdownPeriod: -24.8,
      largestOneDayMove: 13.5,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Dencun Blob Expansion Adoption",
          date: "Oct 12, 2025",
          category: "Layer 2",
          description: "Rollup settlement costs dropped 99%, driving L2 transaction volumes to all-time highs.",
        },
      ],
    },
  },
  sol: {
    "1D": {
      assetId: "sol",
      symbol: "SOL",
      name: "Solana",
      period: "1D",
      startDate: "2026-09-05T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 194.3,
      endPriceUsd: 218.4,
      usdChangePercent: 12.4,
      volatilityAnnualized: 58.2,
      maxDrawdownPeriod: -2.1,
      largestOneDayMove: 12.4,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Firedancer Mainnet Phase 2 Upgrade",
          date: "Sep 5, 2026",
          category: "Validator",
          description: "C++ independent validator client surpassed 1,000,000 TPS hardware stress testing on mainnet.",
        },
      ],
    },
    "7D": {
      assetId: "sol",
      symbol: "SOL",
      name: "Solana",
      period: "7D",
      startDate: "2026-08-30T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 178.5,
      endPriceUsd: 218.4,
      usdChangePercent: 22.35,
      volatilityAnnualized: 64.0,
      maxDrawdownPeriod: -4.5,
      largestOneDayMove: 12.4,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "DEX Volume Dominance Surpasses L1 Competitors",
          date: "Sep 3, 2026",
          category: "Trading",
          description: "24h decentralized trade volume reached 26.4% market dominance across all blockchain ecosystems.",
        },
      ],
    },
    "30D": {
      assetId: "sol",
      symbol: "SOL",
      name: "Solana",
      period: "30D",
      startDate: "2026-08-07T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 148.0,
      endPriceUsd: 218.4,
      usdChangePercent: 47.57,
      volatilityAnnualized: 71.5,
      maxDrawdownPeriod: -11.2,
      largestOneDayMove: 14.8,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Visa & Stripe Settlement Expansion",
          date: "Aug 14, 2026",
          category: "Adoption",
          description: "Merchant USDC settlement on Solana processed over $12B in monthly institutional velocity.",
        },
      ],
    },
    "90D": {
      assetId: "sol",
      symbol: "SOL",
      name: "Solana",
      period: "90D",
      startDate: "2026-06-08T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 125.0,
      endPriceUsd: 218.4,
      usdChangePercent: 74.72,
      volatilityAnnualized: 78.2,
      maxDrawdownPeriod: -19.5,
      largestOneDayMove: 16.5,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Token Extensions Enterprise Rollout",
          date: "Jun 28, 2026",
          category: "Compliance",
          description: "Confidential transfer hooks and interest-bearing asset standard adopted by 40+ fintech partners.",
        },
      ],
    },
    "1Y": {
      assetId: "sol",
      symbol: "SOL",
      name: "Solana",
      period: "1Y",
      startDate: "2025-09-06T09:00:00Z",
      endDate: "2026-09-06T09:00:00Z",
      startPriceUsd: 82.0,
      endPriceUsd: 218.4,
      usdChangePercent: 166.34,
      volatilityAnnualized: 85.0,
      maxDrawdownPeriod: -28.1,
      largestOneDayMove: 21.4,
      dataProvider: "CoinGecko Primary / CoinMarketCap",
      eventsTimeline: [
        {
          title: "Daily Active Wallets Exceed 4.8M",
          date: "Dec 05, 2025",
          category: "Metrics",
          description: "Highest user engagement density recorded across all Layer 1 blockchain networks.",
        },
      ],
    },
  },
};

export class HistoricalPriceService {
  /**
   * Fetch historical data point for asset and period
   */
  public static getHistoricalData(assetId: string, period: "1D" | "7D" | "30D" | "90D" | "1Y" | "CUSTOM" = "1D"): HistoricalDataPoint {
    const assetMap = HISTORICAL_ASSET_DATABASE[assetId.toLowerCase()] || HISTORICAL_ASSET_DATABASE.kryptos;
    const dataPoint = assetMap[period] || assetMap["1D"] || HISTORICAL_ASSET_DATABASE.kryptos["1D"];
    return dataPoint;
  }
}
